### ISSUE TITLE
Add interim mechanism to select current party via query parameter

### ISSUE THREAD

**Issue by elsand** [digdir/dialogporten-frontend#1172] opened 2024-09-26 12:46 UTC
### Description

As a external portal I want to be able to signal Arbeidsflate about currently selected party so that the end-users can navigate between portals keeping the same representational context

### Additional Information

Users might log in to skatteetaten.no or other portals utilizing a party selector similar to the one we have in Arbeidsflate (based on the same data in Altinn Authorization) in which the user may switch between the various parties that they may represent. 

In order to preserve this context when navigating between the different portals, it is desirable to be able to indicate to the target portal the currently selected party.

Scope for this issue is an interim solution only handling passing of selected **organization** context, not **person** context, using query parameters which is required in order to support redirects and SSO roundtrips to ID-porten.

(At some point in the future, a general solution will have to be established allowing for secure and confidential exchange of any data required to preserve this context. This will have to be investigated, and is out-of-scope for this issue)

### Tasks

```[tasklist]
- [ ] Add support for supplying a "party" query parameter to any non-details view in Arbeidsflate
```

### Acceptance Criterias

GIVEN a request to Arbeidsflate that should result in a list of dialogs
WHEN the query parameter "party" is supplied containing a party identifier beginning with "urn:altinn:organization"
AND the full party id is in the currently authenticated users party list
THEN the currently selected party should be set to the provided organization

**Comment by seanes** [comment] 2024-09-30 06:04
Could this wait until masking of party URN for type=`person` is in place? **Assuming** of course that is the main motivation for leaving out personal information in query parameter.  (Creating a URI schema with state that can be partially rehydrated depending on the type of data, is brittle by design.)

... if not (i.e. neither the main motivation or it can wait), propose/clarify scope and technical solution to:

- add query `selectedOrganizations` which can be rehydrated in Arbeidsflate with following logic:
          - empty list (or undefined) or invalid or ineligible parties=> ignored by client
          - if list (of one or more _valid_ organization parties) is an available option in the list of "selected current party", this will be 
         preselected. 
          
This is out of scope:
- AF should not add, modify or later on in the SPA's life cycle respect `selectedOrganizations` (only read after `parties` are successfully fetched).

**Closed** 2024-10-03 07:38 UTC
Labels: dev
